// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const fibSeq = () => {
	let fibs = [1, 2];
	for (let i = 0; i < fibs.length; i++) {
		let nextFib = fibs[i] + fibs[i + 1];
		if (nextFib < 4000000) {
			fibs.push(nextFib);
		}
	}
	return fibs.filter(n => n % 2 === 0).reduce((a, b) => a + b);
};

console.log(fibSeq());
// Result: 4613732
