// Pentagon numbers
// Problem 44
// Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

const getPentagonals = (upperLimit) => {
	const results = [];
	for (let i = 1; i <= upperLimit; i++) {
		const pentagonal = (i * (3 * i - 1)) / 2;
		results.push(pentagonal);
	}

	return results;
};

const getSpecialPentagonals = () => {
	console.time('timer');
	const pentagonals = getPentagonals(10000);
	for (let j = 0; j < pentagonals.length; j++) {
		for (let k = j + 1; k < pentagonals.length; k++) {
			const sum = pentagonals[j] + pentagonals[k];
			const diff = pentagonals[k] - pentagonals[j];
			// did some research and found that the first pair that fulfills the criteria below is the correct answer
			// this function would not be able to exit as early without that prior knowledge
			// wondering how to refine so that I can check fewer numbers
			if (pentagonals.includes(sum) && pentagonals.includes(diff)) {
				console.timeEnd('timer');
				return diff;
			}
		}
	}

	console.timeEnd('timer');
	return 'No such value found';
};

console.log(getSpecialPentagonals()); //5482660
