// Triangular, pentagonal, and hexagonal
// Problem 45
// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

// Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
// Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
// Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
// It can be verified that T285 = P165 = H143 = 40755.

// Find the next triangle number that is also pentagonal and hexagonal.

const isTriangleNumber = (idx, num) => (idx * (idx + 1)) / 2 === num;

const isPentagonalNumber = (idx, num) => (idx * (3 * idx - 1)) / 2 === num;

const isHexagonalNumber = (idx, num) => idx * (2 * idx - 1) === num;

const findNextTriPentHexNum = () => {
	let current = 40755;
	let tIdx = 285;
	let pIdx = 165;
	let hIdx = 143;
	let found = false;
	while (!found) {
		current++;
		if (isTriangleNumber(tIdx + 1, current)) {
			tIdx++;
		}

		if (isPentagonalNumber(pIdx + 1, current)) {
			pIdx++;
		}

		if (isHexagonalNumber(hIdx + 1, current)) {
			hIdx++;
		}

		if (
			isTriangleNumber(tIdx, current) &&
			isPentagonalNumber(pIdx, current) &&
			isHexagonalNumber(hIdx, current)
		) {
			found = current;
		}
	}

	return found;
};

console.log(findNextTriPentHexNum()); //1533776805
